# Generated by Django 6.0.5 on 2026-06-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voter_name',
        ),
        migrations.AddField(
            model_name='vote',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vote',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
