# Generated by Django 6.0.5 on 2026-06-09 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_rename_phone_vote_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='quantity',
            new_name='votes',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='amount',
        ),
        migrations.AddField(
            model_name='vote',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vote',
            name='voter_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='nominee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='awards.nominee'),
        ),
    ]
