# Generated by Django 6.0.5 on 2026-06-10 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_rename_quantity_vote_votes_remove_vote_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominee_name', models.CharField(max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField()),
                ('nominator_name', models.CharField(max_length=255)),
                ('nominator_phone', models.CharField(max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awards.category')),
            ],
        ),
    ]
