# Generated by Django 6.0.5 on 2026-06-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_nomination'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='nominations/'),
        ),
    ]
