# Generated by Django 6.0.5 on 2026-06-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0005_nomination_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
